from DiffEqLibrary import DiffEqLibrary_ as fp

''' First, it is necessary giving to the programme,by the setting_parameters.txt file, the variables to build the initial state of the bar: 
the time of the simulation (float), the lenght of the bar (float), the three temperatures of the two thermostats (float) and of the bar at the beginning of the simulation (float).'''
parameters=fp.parameters_setting('setting_parameters.txt')


''' Secondly, the funcion bar-build generates the initial configuration of the array representing the bar.''' 
initial_bar = fp.bar_builder_well(parameters['temperature_left'],parameters['temperature_right'],parameters['temperature_bar'], parameters['well_position'], parameters['temperature_well'], parameters['lenght'])

''' Third, the functions correlated to the finite difference methods are applied on the initial bar to obtain the evolution of the temperature along the bar in time.
In this case, the method DuFortFrankel is selected to compute the develop of the simulation.'''
final_bar   = fp.DFF_well(parameters['lenght'],parameters['time'],initial_bar,parameters['well_position'])

# Then, it is possible to work on the representation of the simulation. 

''' The function graph_time_t permits to visualize the temperature profile in one istant of the simulation (float);
in this case, the istant chosen correspond to the entire time of the simulation over 2. '''
fp.graph_time_t(parameters['lenght'],parameters['time'],parameters['time']/2,final_bar)

'''The function plot_3d represents the entire evolution of the bar temperature profile during the simulation time,
by a reproduction of a 3D plot (Time vs Space vs Temperature).'''
fp.plot_3D (parameters['lenght'],parameters['time'],final_bar)

''' The function plot_evolution represents the entire evolution of the bar temperature profile during the simulation time by an animation;
the clock permits to visualize the istant of each profile. '''
fp.plot_evolution(parameters['lenght'],parameters['time'],final_bar)

''' The function methods_comparison_well permits to visualize the temperature profile in one istant of the simulation (float), 
generated by each of the four finite difference methods; the istant chosen correspond to the end of the simulation. '''
fp.methods_comparison_well(parameters['lenght'],parameters['time'],initial_bar, parameters['well_position'])
